version: '3.8'

services:
  msr:
    container_name: msr
    image: quay.io/staillanibm/stt-hello-world:latest
    ports:
      - "15555:5555"
    env_file:
      - .env
    volumes:
      - ./application.properties:/opt/softwareag/IntegrationServer/application.properties
