apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 2Gi 
  accessModes:
    - ReadWriteMany 
  mountOptions:
    - allow-delete
    - region eu-central-1
    - prefix data/
    - uid=1724
    - allow-other
  csi:
    driver: s3.csi.aws.com 
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: stt-s3-eu
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stt-hello-world
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: "" 
  resources:
    requests:
      storage: 1Gi 


