name: webMethods microservice CI/CD

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: staillansag/stt-hello-world
  IMAGE_VERSION_BASE: "1.0"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:latest .

    - name: Tagging image with specific version
      run: |
        docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION_BASE }}.${{ github.run_number }}

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin

    - name: Push Docker image 
      run: |
        docker push ${{ env.IMAGE_NAME }}:latest 
        docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION_BASE }}.${{ github.run_number }}

    - name: Create Git Tag
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        TAG_NAME=v${{ env.IMAGE_VERSION_BASE }}.${{ github.run_number }}
        gh release create $TAG_NAME --generate-notes 

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    container:
      image: staillansag/ubuntu-cicd:latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Log in to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZ_SP_ID }} -p ${{ secrets.AZ_SP_SECRET }} --tenant ${{ secrets.TENANT_ID }}

    - name: Get AKS credentials
      run: |
        az aks get-credentials --name aks_cluster --resource-group aks_rg --overwrite-existing

    - name: Test Kubernetes connexion
      run: |
        kubectl get nodes  

    - name: Deploy microservice
      run: |
        sed 's/staillansag\/stt-hello-world\:latest/staillansag\/stt-hello-world\:'${{ env.IMAGE_VERSION_BASE }}.${{ github.run_number }}'/g' kubernetes.yml | kubectl apply -f -

    - name: Wait for end of Deployment
      run: |
        kubectl rollout status deployment/stt-hello-world --timeout=300s 

  test:
    needs: deploy
    runs-on: ubuntu-latest
    container:
      image: staillansag/ubuntu-cicd

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Log in to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZ_SP_ID }} -p ${{ secrets.AZ_SP_SECRET }} --tenant ${{ secrets.TENANT_ID }}

    - name: Get AKS credentials
      run: |
        az aks get-credentials --name ${{ vars.AKS_CLUSTER }} --resource-group ${{ vars.AKS_RESOURCE_GROUP }} --overwrite-existing

    - name: Get external IP of K8S service
      run: |
        SERVICE_IP=$(kubectl get service stt-hello-world -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "SERVICE_IP=$SERVICE_IP" >> $GITHUB_ENV

    - name: Get MSR Administrator password
      run: |      
        ADMIN_PASSWORD=$(kubectl get secret stt-hello-world -o jsonpath="{.data.ADMIN_PASSWORD}" | base64 --decode)
        echo "ADMIN_PASSWORD=$ADMIN_PASSWORD" >> $GITHUB_ENV

    - name: Run automated tests
      run: |
        cd ./resources/test
        newman run HelloWorld.postman_collection.json \
          --env-var "url=http://${{ env.SERVICE_IP }}:8080" \
          --env-var "userName=Administrator" \
          --env-var "password=${{ env.ADMIN_PASSWORD }}" \
          --env-var "callerName=newman" 