name: Hello World microservice CI/CD

on:
  push:
    branches:
      - master

env:
  IMAGE_TAG_BASE: staillansag/stt-hello-world
  IMAGE_VERSION_BASE: "1.0"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_TAG_BASE }}:latest .

    - name: Tagging image with specific version
      run: |
        docker tag ${{ env.IMAGE_TAG_BASE }}:latest ${{ env.IMAGE_TAG_BASE }}:${{ env.IMAGE_VERSION_BASE }}.$GITHUB_RUN_NUMBER

    - name: Push Docker image
      run: |
        docker push ${{ env.IMAGE_TAG_BASE }}:latest
        docker push ${{ env.IMAGE_TAG_BASE }}:${{ env.IMAGE_VERSION_BASE }}.$GITHUB_RUN_NUMBER

  deploy:
    needs: build-and-push 
    runs-on: ubuntu-latest
    container:
      image: staillansag/ubuntu-cicd

    steps:
    - name: Log in to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZ_SP_ID }} -p ${{ secrets.AZ_SP_SECRET }} --tenant ${{ secrets.AZ_TENANT_ID }}

    - name: Get AKS credentials
      run: |
        az aks get-credentials --name ${{ vars.AKS_CLUSTER }} --resource-group ${{ vars.AKS_RESOURCE_GROUP }} --overwrite-existing

    - name: Deploy microservice
      run: |
        pwd 
        ls -l
        kubectl apply -f kubernetes.yml