name: Hello World microservice CI/CD

on:
  push:
    branches:
      - master

env:
  IMAGE_TAG_BASE: staillansag/stt-hello-world
  IMAGE_VERSION_BASE: "1.0"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_TAG_BASE }}:latest .

    - name: Tagging image with specific version
      run: |
        docker tag ${{ env.IMAGE_TAG_BASE }}:latest ${{ env.IMAGE_TAG_BASE }}:${{ env.IMAGE_VERSION_BASE }}.$GITHUB_RUN_NUMBER

    - name: Push Docker image
      run: |
        docker push ${{ env.IMAGE_TAG_BASE }}:latest
        docker push ${{ env.IMAGE_TAG_BASE }}:${{ env.IMAGE_VERSION_BASE }}.$GITHUB_RUN_NUMBER
